modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="http://github.com/MineLittlePony/Kirin/issues/"

[[mods]]
modId="kirin"
version="${file.jarVersion}"
displayName="Kirin"
credits=""
authors="Sollace"
description="Gui library"

[[dependencies.kirin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
